name = "highlander-web"
main = "src/worker.ts"
compatibility_date = "2023-12-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "highlander-db"
database_id = "your-d1-database-id" # wrangler d1 create で取得したIDを設定

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

# Routing
[[routes]]
pattern = "your-domain.com/api/*"
zone_name = "your-domain.com"

# Local development
[dev]
port = 8787