name = "highlandirect-pages"
compatibility_date = "2025-08-12"

# D1 Database binding for CloudFlare Pages
[[d1_databases]]
binding = "DB"
database_name = "highlandirect-db"
database_id = "4c827b08-7b7c-484e-9d3b-6e6a153842bb"

# Environment variables for Japan Post API
[vars]
JAPANPOST_API_HOST = "api.da.pf.japanpost.jp"

# CloudFlare Pages Functions configuration
# Pages Functions will automatically detect functions/ directory
# For local development, run: npx wrangler pages dev dist --binding DB:local-db