name = "highlandirect"
main = "src/worker.ts"
compatibility_date = "2023-12-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "highlandirect-db"
database_id = "4c827b08-7b7c-484e-9d3b-6e6a153842bb"

# Environment variables are managed via wrangler secrets and local .env
# Use: wrangler secret put <SECRET_NAME> for sensitive values
# Development values can be set in .dev.vars (not tracked in git)

# Routing
[[routes]]
pattern = "your-domain.com/api/*"
zone_name = "your-domain.com"

# Local development
[dev]
port = 8787